import React, { useState } from 'react';
import { User, Briefcase, GraduationCap, Code, Languages, Users, Wand2, Loader2 } from 'lucide-react';

const GROQ_API_KEY = import.meta.env.VITE_GROQ_API_KEY;

export default function CVForm({ data, updateData }) {
  const [isGenerating, setIsGenerating] = useState(false);

  const generateWithAI = async () => {
    setIsGenerating(true);
    try {
      const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${GROQ_API_KEY}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          model: 'llama-3.3-70b-versatile',
          messages: [
            {
              role: 'system',
              content: 'You are "Jeremie AI", an expert CV generator. Your task is to generate a highly professional, complete, and realistic CV from scratch for a creative professional or tech worker. Output exactly the following JSON structure filled with creative, high-quality, and realistic professional data. Do NOT add any markdown formatting. Return ONLY valid JSON.\n{"personal":{"fullName":"","nationality":"","residentOf":"","dob":"","gender":"","maritalStatus":"","email":"","phone":""},"experience":[{"period":"","title":"","company":"","location":"","summary":"","responsibilities":""}],"education":[{"date":"","institution":"","location":"","degree":"","details":""}],"skills":[{"name":"","level":"","years":""}],"languages":[{"name":"","listening":"","writing":"","speaking":""}],"references":[{"name":"","position":"","phone":"","email":""}]}'
            }
          ],
          temperature: 0.7,
          response_format: { type: "json_object" }
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API Error (${response.status}): ${errorText}`);
      }

      const result = await response.json();
      let generatedDataStr = result.choices[0].message.content.trim();
      
      if (generatedDataStr.startsWith('```json')) {
        generatedDataStr = generatedDataStr.replace(/^```json\n?/i, '').replace(/```$/i, '').trim();
      } else if (generatedDataStr.startsWith('```')) {
        generatedDataStr = generatedDataStr.replace(/^```\n?/i, '').replace(/```$/i, '').trim();
      }
      
      const generatedData = JSON.parse(generatedDataStr);
      
      if (generatedData && typeof generatedData === 'object' && generatedData.personal) {
        updateData(generatedData);
        alert('CV successfully generated by Jeremie AI!');
      } else {
        throw new Error('Invalid JSON structure returned by AI');
      }
    } catch (error) {
      console.error('Failed to generate CV:', error);
      alert(`Failed to generate CV: ${error.message}`);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleChange = (e, section, field, index = null) => {
    const { name, value } = e.target;
    if (index !== null) {
      const newList = [...data[section]];
      newList[index][name] = value;
      updateData({ ...data, [section]: newList });
    } else if (section) {
      updateData({
        ...data,
        [section]: { ...data[section], [name]: value }
      });
    } else {
      updateData({ ...data, [name]: value });
    }
  };

  const addItem = (section, template) => {
    updateData({ ...data, [section]: [...data[section], template] });
  };

  const removeItem = (section, index) => {
    const newList = [...data[section]];
    newList.splice(index, 1);
    updateData({ ...data, [section]: newList });
  };

  return (
    <div className="form-section">
      <h2 className="section-title"><User size={20} /> Personal Information</h2>
      <div className="form-group">
        <label>Full Name</label>
        <input name="fullName" value={data.personal.fullName} onChange={(e) => handleChange(e, 'personal')} placeholder="e.g. NIYOGISUBIZO jeremie" />
      </div>
      <div className="form-row">
        <div className="form-group">
          <label>Nationality</label>
          <input name="nationality" value={data.personal.nationality} onChange={(e) => handleChange(e, 'personal')} />
        </div>
        <div className="form-group">
          <label>Resident of</label>
          <input name="residentOf" value={data.personal.residentOf} onChange={(e) => handleChange(e, 'personal')} />
        </div>
      </div>
      <div className="form-row">
        <div className="form-group">
          <label>Birth Date</label>
          <input name="dob" value={data.personal.dob} onChange={(e) => handleChange(e, 'personal')} placeholder="e.g. 14 Jan, 1973" />
        </div>
        <div className="form-group">
          <label>Gender</label>
          <select name="gender" value={data.personal.gender} onChange={(e) => handleChange(e, 'personal')}>
            <option value="">Select...</option>
            <option value="Male">Male</option>
            <option value="Female">Female</option>
          </select>
        </div>
      </div>
      <div className="form-row">
        <div className="form-group">
          <label>Marital Status</label>
          <input name="maritalStatus" value={data.personal.maritalStatus} onChange={(e) => handleChange(e, 'personal')} />
        </div>
        <div className="form-group">
          <label>Email</label>
          <input name="email" value={data.personal.email} onChange={(e) => handleChange(e, 'personal')} type="email" />
        </div>
      </div>
      <div className="form-row">
        <div className="form-group">
          <label>Phone Number</label>
          <input name="phone" value={data.personal.phone} onChange={(e) => handleChange(e, 'personal')} />
        </div>
      </div>

      <h2 className="section-title"><Briefcase size={20} /> Professional Experience</h2>
      {data.experience.map((exp, index) => (
        <div key={index} className="form-item-card">
          <button className="btn-remove-float" onClick={() => removeItem('experience', index)}>×</button>
          <div className="form-row">
            <div className="form-group"><label>Period</label><input name="period" value={exp.period} onChange={(e) => handleChange(e, 'experience', null, index)} placeholder="e.g. Sept 2005 - Present" /></div>
            <div className="form-group"><label>Job Title</label><input name="title" value={exp.title} onChange={(e) => handleChange(e, 'experience', null, index)} /></div>
          </div>
          <div className="form-row">
            <div className="form-group"><label>Company</label><input name="company" value={exp.company} onChange={(e) => handleChange(e, 'experience', null, index)} /></div>
            <div className="form-group"><label>Location</label><input name="location" value={exp.location} onChange={(e) => handleChange(e, 'experience', null, index)} /></div>
          </div>
          <div className="form-group">
            <label>Short Summary (Optional)</label>
            <textarea name="summary" value={exp.summary} onChange={(e) => handleChange(e, 'experience', null, index)} rows="2"></textarea>
          </div>
          <div className="form-group">
            <label>Responsibilities (One per line)</label>
            <textarea name="responsibilities" value={exp.responsibilities} onChange={(e) => handleChange(e, 'experience', null, index)} rows="5"></textarea>
          </div>
        </div>
      ))}
      <button className="btn-add" onClick={() => addItem('experience', { period: '', title: '', company: '', location: '', summary: '', responsibilities: '' })}>+ Add Experience</button>

      <h2 className="section-title"><GraduationCap size={20} /> Education Background</h2>
      {data.education.map((edu, index) => (
        <div key={index} className="form-item-card">
          <button className="btn-remove-float" onClick={() => removeItem('education', index)}>×</button>
          <div className="form-row">
            <div className="form-group"><label>Date/Period</label><input name="date" value={edu.date} onChange={(e) => handleChange(e, 'education', null, index)} /></div>
            <div className="form-group"><label>Degree/Certification</label><input name="degree" value={edu.degree} onChange={(e) => handleChange(e, 'education', null, index)} /></div>
          </div>
          <div className="form-row">
            <div className="form-group"><label>Institution</label><input name="institution" value={edu.institution} onChange={(e) => handleChange(e, 'education', null, index)} /></div>
            <div className="form-group"><label>Location</label><input name="location" value={edu.location} onChange={(e) => handleChange(e, 'education', null, index)} /></div>
          </div>
          <div className="form-group">
            <label>Additional Details</label>
            <input name="details" value={edu.details} onChange={(e) => handleChange(e, 'education', null, index)} />
          </div>
        </div>
      ))}
      <button className="btn-add" onClick={() => addItem('education', { date: '', institution: '', location: '', degree: '', details: '' })}>+ Add Education</button>

      <h2 className="section-title"><Code size={20} /> Skills</h2>
      {data.skills.map((skill, index) => (
        <div key={index} className="form-row" style={{marginBottom: '0.5rem', alignItems: 'end'}}>
          <input name="name" value={skill.name} onChange={(e) => handleChange(e, 'skills', null, index)} placeholder="Skill name" />
          <input name="level" value={skill.level} onChange={(e) => handleChange(e, 'skills', null, index)} placeholder="Level (e.g. Advanced)" />
          <input name="years" value={skill.years} onChange={(e) => handleChange(e, 'skills', null, index)} placeholder="Years practiced" />
          <button className="btn-remove" onClick={() => removeItem('skills', index)}>×</button>
        </div>
      ))}
      <button className="btn-add" onClick={() => addItem('skills', { name: '', level: '', years: '' })}>+ Add Skill</button>

      <h2 className="section-title"><Languages size={20} /> Languages</h2>
      {data.languages.map((lang, index) => (
        <div key={index} className="form-row language-grid" style={{marginBottom: '0.5rem', alignItems: 'end', gridTemplateColumns: '2fr 1fr 1fr 1fr auto'}}>
          <input name="name" value={lang.name} onChange={(e) => handleChange(e, 'languages', null, index)} placeholder="Language" />
          <input name="listening" value={lang.listening} onChange={(e) => handleChange(e, 'languages', null, index)} placeholder="Listening" />
          <input name="writing" value={lang.writing} onChange={(e) => handleChange(e, 'languages', null, index)} placeholder="Writing" />
          <input name="speaking" value={lang.speaking} onChange={(e) => handleChange(e, 'languages', null, index)} placeholder="Speaking" />
          <button className="btn-remove" onClick={() => removeItem('languages', index)}>×</button>
        </div>
      ))}
      <button className="btn-add" onClick={() => addItem('languages', { name: '', listening: '', writing: '', speaking: '' })}>+ Add Language</button>

      <h2 className="section-title"><Users size={20} /> References</h2>
      {data.references.map((ref, index) => (
        <div key={index} className="form-item-card">
          <button className="btn-remove-float" onClick={() => removeItem('references', index)}>×</button>
          <div className="form-row">
            <div className="form-group"><label>Name</label><input name="name" value={ref.name} onChange={(e) => handleChange(e, 'references', null, index)} /></div>
            <div className="form-group"><label>Position</label><input name="position" value={ref.position} onChange={(e) => handleChange(e, 'references', null, index)} /></div>
          </div>
          <div className="form-row">
            <div className="form-group"><label>Phone</label><input name="phone" value={ref.phone} onChange={(e) => handleChange(e, 'references', null, index)} /></div>
            <div className="form-group"><label>Email</label><input name="email" value={ref.email} onChange={(e) => handleChange(e, 'references', null, index)} /></div>
          </div>
        </div>
      ))}
      <button className="btn-add" onClick={() => addItem('references', { name: '', position: '', phone: '', email: '' })}>+ Add Reference</button>

      <div style={{ display: 'flex', justifyContent: 'center', marginTop: '3rem', paddingTop: '1.5rem', borderTop: '2px dashed #e2e8f0' }}>
        <button 
          onClick={generateWithAI} 
          disabled={isGenerating}
          className="btn-ai-generate"
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: '0.75rem',
            backgroundColor: '#3b82f6',
            color: 'white',
            padding: '0.8rem 1.5rem',
            borderRadius: '0.5rem',
            border: 'none',
            cursor: isGenerating ? 'not-allowed' : 'pointer',
            fontWeight: 'bold',
            fontSize: '1.1rem',
            opacity: isGenerating ? 0.7 : 1,
            transition: 'all 0.2s',
            boxShadow: '0 10px 15px -3px rgba(59, 130, 246, 0.3)'
          }}
        >
          {isGenerating ? <Loader2 size={24} className="animate-spin" /> : <Wand2 size={24} />}
          {isGenerating ? 'Generating full CV...' : 'Generate CV with Jeremie AI 🚀'}
        </button>
      </div>
    </div>
  );
}
